name: Markdown Indexing

on: push

jobs:
  indexing:
    name: Build and Push Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Markdown Index
        run: |
          rm -rf index
          mkdir -p index

          prefix_delim="/"
          filename_delim="--"

          for dir in *; do
            if [ -d "$dir" ] && [ "$dir" != "index" ]; then
              index="index/$dir.md"

              echo "# ${dir^}" > $index
              echo "" >> $index

              for entry in "$dir"/*.md; do
                if [ -f "$entry" ]; then
                  read -r headerline < $entry
                  filename=${entry#*$prefix_delim}
                  date=${filename%%$filename_delim*}
                  echo "- [${headerline:2} ($date)](/$entry)" >> $index
                fi
              done
            fi
          done
      - name: Push Markdown Index
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'dotCliqe CI'
            git config --global user.email 'ci@dotclique.com'
            git add ./index
            git commit -m "Update markdown index"
            git push
          else
            echo "Index unchanged"
          fi
