name: Markdown Indexing

on: push

jobs:
  indexing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build markdown index
        run: |
          mkdir -p index
          
          for dir in *; do
              if [ -d "$dir" ]; then
                  index="index/$dir.md"
          
                  echo "# ${dir^}" > $index
                  echo "" >> $index
          
                  for entry in "$dir"/*.md; do
                      if [ -f "$entry" ]; then
                          read -r headerline < $entry
                          echo "- [${headerline:2}]($entry)" >> $index
                      fi
                  done
              fi
          done
      - name: Push index
        run: |
          git config --global user.name 'dotCliqe CI'
          git config --global user.email 'ci@dotclique.com'
          git add ./index
          git commit -m "Update markdown index"
          git push
